### ISSUE TITLE
NewEtcdV3DiscoveryStore流程不科学

### ISSUE THREAD

**Issue by zealass** [rpcxio/rpcx-etcd#12]
NewEtcdV3DiscoveryStore里的
ps, err := kv.List(basePath)这个getall逻辑应该在每次watch成功后都执行一次

**Comment by smallnest** [comment]
为什么？这个事件获取到的是所有的节点信息。 你是遇到问题了还是感觉有问题？

**Comment by zealass** [comment]
先取全部，再监控，这个中间有N-ns的数据没同步
本机多跑跑就能跑出这个问题，可以这么放大问题测试：getall，sleep(N-sec)，watch
应该每次监控成功后，取全部
