### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by xfye** [rpcxio/rpcx-etcd#3]
github.com/rpcxio/rpcx-etcd@v0.0.0-20201229103411-8317fc934fbb requires
        go.etcd.io/etcd@v3.4.14+incompatible: reading https://goproxy.cn/go.etcd.io/etcd/@v/v3.4.14+incompatible.mod: 404 Not Found

**Comment by smallnest** [comment]
编译是没问题的，看readme中的ci build图标就直到了。 3.4.14是
```
go.etcd.io/etcd v3.4.14+incompatible/go.mod h1:yVHk9ub3CSBatqGNg7GRmsnfLWtoW60w4eDYfh7vHDg=
```

你这个可以从下面三个追查原因：

1. 你的go是不熟最新的1.15版本
2. goproxy.cn的问题
3. go.etcd.io网站问题

**Comment by smallnest** [comment]
使用 goproxy.io做代理，不要使用goproxy.cn或者ali的proxy试试，应该可以。

```
 go env -w GOPROXY=https://goproxy.io,direct
```
